### ISSUE TITLE
Get utility WPS time bounds algorithm working with noleap and other calendars.

### ISSUE THREAD

**Issue by dblodgett-usgs** [USGS-CIDA/geo-data-portal#216]
It appears that standard date units are used when there should be calendar date units.  First pass might be to remove the return statements, though that is just at a quick glance.

https://github.com/USGS-CIDA/geo-data-portal/blob/master/gdp-data-access/src/main/java/gov/usgs/cida/gdp/dataaccess/helper/OpendapServerHelper.java#L158

**Comment by jiwalker-usgs** [comment]
Add unit test to test the expected behavior, this may just be fixed with NetCDF-Java upgrade.

**Comment by dblodgett-usgs** [comment]
@jiwalker-usgs This is fixed right?

**Comment by jiwalker-usgs** [comment]
Yes.

**Comment by dblodgett-usgs** [comment]
Cool.
