### ISSUE TITLE
Make OPeNDAP requests across multiple time steps.

### ISSUE THREAD

**Issue by dblodgett-usgs** [USGS-CIDA/geo-data-portal#219]
This issue will likely spawn a lot more requirements, but it is becoming clear that the GDP needs to make requests for reasonable 'chunks' of data rather than one time step at a time. 

Commonly, a single request to the GDP spans >100,000 individual timesteps. As implemented, even if the request is for only a few grid cells, one web request is made per timestep. This is good for ultimate scalability, but is problematic for small-area long time period requests. If we could make requests for more reasonable chunks of data, say a set data volume, size informed by stated chunk sizes, or even an adaptive size, we could get much better throughput of an overall process.

**Comment by jread-usgs** [comment]
see #255
