### ISSUE TITLE
Heuristic for summary output size estimates too big

### ISSUE THREAD

**Issue by jiwalker-usgs** [USGS-CIDA/geo-data-portal#229]
This code

https://github.com/USGS-CIDA/geo-data-portal/blob/master/gdp-process-wps/src/main/java/gov/usgs/cida/gdp/wps/algorithm/heuristic/SummaryOutputSizeAlgorithmHeuristic.java

works fine for one variable, but in the case of multiple it gets run several times and returns a size that is not accurate.  The creation of this and the other heuristics should only take place once, but it is happening within a loop:

https://github.com/USGS-CIDA/geo-data-portal/blob/master/gdp-process-wps/src/main/java/gov/usgs/cida/gdp/wps/algorithm/FeatureWeightedGridStatisticsAlgorithm.java#L239

Which causes it to run multiple times and result in huge estimates.

**Comment by dblodgett-usgs** [comment]
Fixed.
