### ISSUE TITLE
Analytics for how much data was traversed.

### ISSUE THREAD

**Issue by jread-usgs** [USGS-CIDA/geo-data-portal#252]
- How many time steps
- Spatial data dimensions (grid dimensions)
- Data type (e.g., int)
- Bounding rectangle (four corners)
- Number of variables
- Associated with job id.

**Comment by jiwalker-usgs** [comment]
@jread-usgs the discussion around bounding rectangle got confusing, which four corners are we talking about with this?

**Comment by jiwalker-usgs** [comment]
![image](https://cloud.githubusercontent.com/assets/1173041/24524594/c837139c-155c-11e7-8bd3-0dc942b4b64a.png)

**Comment by dblodgett-usgs** [comment]
IMHO, 1,2,3,4 are the corners that are relevant to how much data was traversed. The bounding rectangle is the lat / lon of those corners. The corners of the data cube that was required to cover the analysis area. But maybe others will disagree.

**Comment by jiwalker-usgs** [comment]
All these are done but job id, I think this probably needs to be discussed a bit further.  Thoughts @jread-usgs

**Comment by jiwalker-usgs** [comment]
tested on dev, output size is giving troubles still

**Comment by jread-usgs** [comment]
yes, 1, 2, 3, & 4 are what I have for the cube.

**Comment by jiwalker-usgs** [comment]
Done with the first round on this, will need to loop back to capture job id concept
