### ISSUE TITLE
Add % Complete Status in database

### ISSUE THREAD

**Issue by jread-usgs** [USGS-CIDA/geo-data-portal#254]

**Comment by jread-usgs** [comment]
- get the math into the visitor to calculate % complete (as we loop through the processing). Figure out total, update as we move through.
- Figure out how the heuristics get to the database (only hooked up now for user-agent, and that is kind of hacky). May want to pull this out into separate database.
- We don't want to slow down the processing by doing hops to database. Have a reporting thread for DB so we can be async. 
- get ☕️

**Comment by jiwalker-usgs** [comment]
This is working for some of the algorithms, we will need to come up with a plan to get it in other algorithms.

**Comment by dblodgett-usgs** [comment]
Which ones does it work for?!?

**Comment by jiwalker-usgs** [comment]
grid statistics (weighted and unweighted) and maybe categorical

**Comment by jiwalker-usgs** [comment]
Calling this good for now, we should test it out a bit and make follow up tickets to improve or extend to other algorithms.
