### ISSUE TITLE
Make Analytics Data Accessible.

### ISSUE THREAD

**Issue by jread-usgs** [USGS-CIDA/geo-data-portal#256]
- add columns to JSON report (needs a join and mapping)
- user-agent, % complete, unique user ID, other analytics data
- query params (if possible?) such as status=ACCEPTED. Are we covered on security for SQL injections?

Is there anything in here that isn't 1:1? Don't expose it if so (this also complicates the join).

**Comment by jiwalker-usgs** [comment]
fixed by #263

**Comment by jiwalker-usgs** [comment]
Also #262
