### ISSUE TITLE
Jobs erroring on test GDP

### ISSUE THREAD

**Issue by wchen329** [USGS-CIDA/geo-data-portal#277]
**Migrated from: GDP-1106:**
*Originally reported by wdwatkins*

Jobs utilizing external datasets hosted on a newer version of THREDDS starting failing a while back with inconsistent array length errors. Jordan Walker implemented some features that fixed this, and are deployed to cida-test, but are now causing different errors.

One job fails with "General Error: null", the other with "General Error: Stopwatch already started."

I suspect the stopwatch error is related to this code: https://github.com/USGS-CIDA/geo-data-portal/blob/e45b0de84d756fa3c0cb91eff894e85a06d29c05/gdp-process-wps/src/main/java/gov/usgs/cida/gdp/wps/algorithm/heuristic/TotalTimeAlgorithmHeuristic.java

Could break this into two issues if the errors turn out to be totally unrelated.

**Comment by wchen329** [comment]
[JIRA_GDP-1106-attachments.zip](https://github.com/USGS-CIDA/geo-data-portal/files/2484047/JIRA_GDP-1106-attachments.zip)

**Comment by isuftin** [comment]
This has been fixed in the latest release. Thank you for including the sample requests, @wchen329
